/*
 * SERVOMOTOR_config.h
 *
 *  Created on: Aug 4, 2022
 *      Author: DELL
 */

#ifndef HAL_SERVOMOTOR_SERVOMOTOR_CONFIG_H_
#define HAL_SERVOMOTOR_SERVOMOTOR_CONFIG_H_



#endif /* HAL_SERVOMOTOR_SERVOMOTOR_CONFIG_H_ */
